### ISSUE TITLE
POS format error, no customer

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/pos-zaviago#12]
POS Format (POS Invoice doctype) will return as an error if format have no customer selected.

**How to reproduce.**

1. Remove customer make sure customer is blank.
![Image](https://github.com/zaviagodev/pos-zaviago/assets/120152434/83df9d1e-a6d1-4706-8d93-cdd82cf07747)

2. select any item to cart.
3. print draft.

**Comment by Muzmal** [comment]
@chomchuen  @deviljutt will fix this from code level. It is from backend.

**Comment by chomchuen** [comment]
Noted. I'll move this issue to Nabeel.
